apiVersion: skaffold/v1beta2
kind: Config
build:
    local:
        push: false # Whenever skaffold builds an image, it will push that to docker hub, therefore we disable that. 
    artifacts:
        - image: bpremkumar/multi-client # We are just doing client, but we have to do this for all server and worker as well. 
          context: client
          docker: 
            dockerfile: Dockerfile.dev
          sync:
            '**/*.js': . # Any js changes, sync it with the container
            '**/*.css': .
            '**/*.html': .
        - image: bpremkumar/multi-server
          context: server
          docker:
            dockerfile: Dockerfile.dev
          sync:
            '**/*.js': .
        - image: bpremkumar/multi-worker
          context: worker
          docker:
            dockerfile: Dockerfile.dev
          sync:
            '**/*.js': .
deploy:
    kubectl:
        manifests:
            - k8s/client-deployment.yaml
            - k8s/server-deployment.yaml
            - k8s/worker-deployment.yaml
            - k8s/server-cluster-ip-service.yaml
            - k8s/client-cluster-ip-service.yaml


