apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
spec:
    replicas: 3 
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web #Selector and this should be identical
        spec:
            containers:
                - name: client
                  image: bpremkumar/multi-client
                  ports:
                    - containerPort: 3000